version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/init.sql
  
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=geu_costa@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=987456
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
volumes:
  data:
