version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data:
